* Scramble

  This is an exploratory project for the usage of =Clojure= and
  =ClojureScript=. It's made of only two simple parts:

  - A Web Server (that handles HTTP requests);
  - And a UI Application (that talks to the web server).

  The Web Server has only one valid route, i.e., =/scramble=, which
  receives two string values as query parameters. The UI Application
  is nothing but a two field form and a submit button that sends the
  expected two strings to the server.

** Project Depencies

   Packages:
   - Clojure
   - leiningen

   Clojure Modules:
   - org.clojure/clojure
   - compojure
   - http-kit
   - org.clojure/clojurescript
   - reagent
   - re-frame
   - day8.re-frame/http-fx

** Web Server

   All source files are contained in the =scramble/= directory,
   alongside more detailed descriptions in its [[file:scramble/README.org][README]] file.

*** How to run

    Use =leiningen= to run the server:

    #+BEGIN_SRC sh
    > cd scramble/
    > lein run
    #+END_SRC

    You can also use =Docker/Docker Compose= in case you don't have or
    wish to have all the dependecies in your local environment.

    First, build, create and start the container with the virtual
    environment by running:

    #+BEGIN_SRC sh
    > docker-compose up -d
    #+END_SRC

    This approach avoids having to reinstall the dependecies every time
    the container is created, especially because there isn't an obvious
    way of "pre-installing" the project dependencies using =leiningen=.

    Now, run the server:

    #+BEGIN_SRC sh
    > docker-compose exec -w '/scramble-api' scramble-env sh -c "lein run"
    #+END_SRC

** UI Application

   All source files are contained in the =scramble-frontend/=
   directory, alongside more detailed descriptions in its [[file:scramble-frontend/README.org][README]] file.

*** How to run

    To build the page, again, use =leiningen=:

    #+BEGIN_SRC sh
    > cd scramble-frontend/
    > lein cljsbuild once dev
    #+END_SRC

    If you wish to tweak the code, you can also have it automatically
    rebuild the page, in case of changes, by running:

    #+BEGIN_SRC sh
    > cd scramble-frontend/
    > lein cljsbuild auto dev
    #+END_SRC

    Or, using =Docker/Docker Compose= (remember to build/start the
    container):

    #+BEGIN_SRC sh
    > docker-compose exec -w '/scramble-frontend' scramble-env sh -c "lein cljsbuild once dev"
    #+END_SRC

    Or, have it watch for changes with:

    #+BEGIN_SRC sh
    > docker-compose exec -w '/scramble-frontend' scramble-env sh -c "lein cljsbuild auto dev"
    #+END_SRC

    Since there's no =HTTP Server= providing this frontend, please,
    open the file located at
    =scramble-frontend/resources/public/index.html= in your preferred
    browser.
